<?php
return [
    'admin'=>'admin',
    'student'=>'student',
    'guest'=>'guest',
    'leagueWin'=>30,
    'win'=>3,
    'tie'=>1,
    'loss'=>0,
    'honor'=>1,
    'goal'=>1,
    'redCard'=>-2,
    'yellowCard'=>-1,
    'save'=>1,
    'defence'=>1,
    'assists'=>1,
    'rightPrediction'=>1,
    'wrongPrediction'=>0,
    'undeclared'=>'undeclared',
    'declared'=>'Declared',
    'finished'=>'Finished',
    'matchError'=>'MatchError'       
];