<?php
return [
    'admin'=>'admin',
    'student'=>'student',
    'guest'=>'guest',
    'win'=>50,
    'tie'=>20,
    'loss'=>-50,
    'honor'=>30,
    'goal'=>30,
    'redCard'=>-30,
    'yellowCard'=>-20,
    'save'=>30,
    'defence'=>15,
    'assists'=>15,
    'rightPrediction'=>15,
    'wrongPrediction'=>15,
    'undeclared'=>'undelcared',
    'declared'=>'Declared',
    'finished'=>'Finished',
    'matchError'=>'MatchError'       
];